sudo: required

language: node

services:
  - docker

matrix:
  include:
#    - env: IMPL=awk
#      os: linux
#    - env: IMPL=bash
#      os: linux
#    - env: IMPL=c
#      os: linux
#    - env: IMPL=cpp
#      os: linux
#    - env: IMPL=coffee
#      os: linux
#    - env: IMPL=cs
#      os: linux
#    - env: IMPL=clojure
#      os: linux
#    - env: IMPL=crystal
#      os: linux
#    - env: IMPL=elixir
#      os: linux
#    - env: IMPL=erlang
#      os: linux
#    - env: IMPL=es6
#      os: linux
#    - env: IMPL=factor
#      os: linux
#    - env: IMPL=forth
#      os: linux
#    - env: IMPL=fsharp
#      os: linux
#    - env: IMPL=go
#      os: linux
#    - env: IMPL=groovy
#      os: linux
#    - env: IMPL=guile
#      os: linux
#    - env: IMPL=haskell
#      os: linux
#    - env: IMPL=java
#      os: linux
#    - env: IMPL=js
#      os: linux
#    - env: IMPL=julia
#      os: linux
#    - env: IMPL=lua
#      os: linux
#    - env: IMPL=make
#      os: linux
#    - env: IMPL=mal BUILD_IMPL=js
#      os: linux
#    #- env: IMPL=matlab  # licensed (until port to Octave)
#    #  os: linux
#    #- env: IMPL=miniMAL  # repl/string slice bug
#    #  os: linux
#    - env: IMPL=nim
#      os: linux
#    - env: IMPL=ocaml
#      os: linux
#    - env: IMPL=perl
#      os: linux
#    - env: IMPL=php
#      os: linux
#    - env: IMPL=ps
#      os: linux
#    - env: IMPL=python
#      os: linux
#    - env: IMPL=r
#      os: linux
#    - env: IMPL=racket
#      os: linux
#    - env: IMPL=rpython
#      os: linux
#    - env: IMPL=ruby
#      os: linux
#    - env: IMPL=rust
#      os: linux
#    - env: IMPL=scala
#      os: linux
    - env: IMPL=swift
      os: osx
#    - env: IMPL=vb
#      os: linux

script:
  - docker pull kanaka/mal-test-${IMPL,,}
  - BUILD_IMPL=${BUILD_IMPL:-${IMPL}} && docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${BUILD_IMPL,,} make -C ${BUILD_IMPL}
  - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${IMPL,,} make TEST_OPTS="--soft --log-file ../run.out" test^${IMPL}
  - cat run.out
    #- docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${IMPL,,} make perf^${IMPL}
