sudo: required

language: node

services:
    - docker

env:
    - IMPL=awk
    - IMPL=bash
    - IMPL=c
    - IMPL=cpp
    - IMPL=coffee
    - IMPL=cs
    - IMPL=clojure
    - IMPL=crystal
    - IMPL=elixir
    - IMPL=erlang
    - IMPL=es6
    - IMPL=factor  # stepA optional failures
    - IMPL=forth
    - IMPL=fsharp
    - IMPL=go
    - IMPL=groovy  # stepA conj failures
    #- IMPL=guile  # step0 regex issues
    - IMPL=haskell
    - IMPL=java
    - IMPL=js
    - IMPL=julia  # stepA optional failures
    - IMPL=lua
    - IMPL=make
    - IMPL=mal
    #- IMPL=matlab  # licensed (until port to Octave)
    - IMPL=miniMAL  # repl/string slice bug
    - IMPL=nim
    - IMPL=ocaml
    - IMPL=perl
    - IMPL=php
    - IMPL=ps
    - IMPL=python
    - IMPL=r
    - IMPL=racket  # stepA optional failures
    #- IMPL=rpython  # very long build
    - IMPL=ruby
    - IMPL=rust  # compilation issues
    - IMPL=scala
    #- IMPL=swift  # OS X, need travis-ci multi-language support
    - IMPL=vb

script:
    - docker pull kanaka/mal-test-${IMPL,,}
    - if [ "${IMPL}" = "mal" ]; then docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-js make -C js;  else docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${IMPL,,} make -C $IMPL; fi
    - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${IMPL,,} make TEST_OPTS="--log-file ../run.out" test^${IMPL}
    - cat run.out
      #- docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${IMPL,,} make perf^${IMPL}
