sudo: required

language: node

services:
    - docker

env:
    - IMPL=bash
    - IMPL=c
    - IMPL=cpp
    #- IMPL=coffee  # step5 hangs
    - IMPL=cs
    - IMPL=clojure
    - IMPL=factor
    - IMPL=forth
    - IMPL=go
    - IMPL=haskell
    - IMPL=java
    - IMPL=js
    - IMPL=julia
    - IMPL=lua
    - IMPL=make
    - IMPL=mal
    #- IMPL=matlab  # licensed (until port to Octave)
    #- IMPL=miniMAL  # repl/string slice bug
    - IMPL=nim
    - IMPL=ocaml
    - IMPL=perl
    - IMPL=php
    - IMPL=ps
    - IMPL=python
    - IMPL=r
    #- IMPL=racket  # stepA optional failures
    - IMPL=ruby
    #- IMPL=rust  # compilation issues
    - IMPL=scala
    #- IMPL=swift  # OS X, need travis-ci multi-language support
    - IMPL=vb

script:
    - docker pull kanaka/mal-test-${IMPL,,}
    - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${IMPL,,} make -C $IMPL
    - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${IMPL,,} make test^${IMPL}
