sudo: required

language: node

services:
    - docker

env:
    - IMPL=bash
    - IMPL=c
    - IMPL=clojure
    - IMPL=java
    - IMPL=js
    - IMPL=make
    - IMPL=php
    - IMPL=ps
    - IMPL=python

script:
    - docker pull kanaka/mal-test-$IMPL
    - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-$IMPL make -C $IMPL
    - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-$IMPL make IMPLS="$IMPL" test
