sudo: required

language: node

services:
    - docker

env:
    - IMPL=bash
    - IMPL=c
    #- IMPL=coffee  # step5 hangs
    - IMPL=cs
    - IMPL=clojure
    - IMPL=go
    - IMPL=java
    - IMPL=js
    - IMPL=make
    - IMPL=perl
    - IMPL=php
    - IMPL=ps
    - IMPL=python
    - IMPL=r
    - IMPL=ruby
    - IMPL=rust
    - IMPL=vb

script:
    - docker pull kanaka/mal-test-$IMPL
    - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-$IMPL make -C $IMPL
    - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-$IMPL make IMPLS="$IMPL" test
