sudo: required

language: node

services:
  - docker

env:
  #global:
  matrix:
    - IMPL=awk
    - IMPL=bash
    - IMPL=c
    - IMPL=cpp
    - IMPL=coffee
    - IMPL=cs
    - IMPL=clojure
    - IMPL=crystal
    - IMPL=elixir
    - IMPL=erlang
    - IMPL=es6
    - IMPL=factor
    - IMPL=forth
    - IMPL=fsharp
    - IMPL=go
    - IMPL=groovy
    #- IMPL=guile  # step0 regex issues
    - IMPL=haskell
    - IMPL=java
    - IMPL=js
    - IMPL=julia
    - IMPL=lua
    - IMPL=make
    - IMPL=mal BUILD_IMPL=js
    #- IMPL=matlab  # licensed (until port to Octave)
    - IMPL=miniMAL  # repl/string slice bug
    - IMPL=nim
    - IMPL=ocaml
    - IMPL=perl
    - IMPL=php
    - IMPL=ps
    - IMPL=python
    - IMPL=r
    - IMPL=racket
    - IMPL=rpython
    - IMPL=ruby
    - IMPL=rust
    - IMPL=scala
    #- IMPL=swift  # OS X, need travis-ci multi-language support
    - IMPL=vb

script:
  - docker pull kanaka/mal-test-${IMPL,,}
  - BUILD_IMPL=${BUILD_IMPL:-${IMPL}} && docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${BUILD_IMPL,,} make -C ${BUILD_IMPL}
  - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${IMPL,,} make TEST_OPTS="--soft --log-file ../run.out" test^${IMPL}
  - cat run.out
    #- docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${IMPL,,} make perf^${IMPL}
