sudo: required

language: node

services:
    - docker

env:
    - IMPL=bash
    - IMPL=c
    #- IMPL=coffee  # step5 hangs
    - IMPL=cs
    - IMPL=clojure
    - IMPL=forth
    - IMPL=go
    - IMPL=haskell
    - IMPL=java
    - IMPL=js
    - IMPL=lua
    - IMPL=make
    #- IMPL=matlab  # licensed (until port to Octave)
    - IMPL=miniMAL
    - IMPL=ocaml
    - IMPL=perl
    - IMPL=php
    - IMPL=ps
    - IMPL=python
    - IMPL=r
    #- IMPL=racket  # stepA optional failures
    - IMPL=ruby
    #- IMPL=rust  # compilation issues
    - IMPL=scala
    - IMPL=vb

script:
    - docker pull kanaka/mal-test-${IMPL,,}
    - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${IMPL,,} make -C $IMPL
    - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-${IMPL,,} make IMPLS="$IMPL" test
