sudo: required

language: node

services:
    - docker

env:
    - IMPL=js
    - IMPL=python

script:
    - docker pull kanaka/mal-test-$IMPL
    - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-$IMPL make -C $IMPL
    - docker run -it -u $(id -u) -v `pwd`:/mal kanaka/mal-test-$IMPL make IMPLS="$IMPL" test
